# Generated by Django 4.1.7 on 2023-03-13 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("culinary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="calories",
            field=models.FloatField(
                help_text="number of calories in kcal per 100 grams",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="carbs",
            field=models.FloatField(
                help_text="amount of carbs in kcal per 100 grams",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fruits", "Fruits"),
                    ("Vegetables", "Vegetables"),
                    ("Meat", "Meat"),
                    ("Poultry", "Poultry"),
                    ("Fish", "Fish"),
                    ("Seafood", "Seafood"),
                    ("Milk", "Milk"),
                    ("Eggs", "Eggs"),
                    ("Baking", "Baking"),
                    ("Grains", "Grains"),
                    ("Beans", "Beans"),
                    ("Seasonings", "Seasonings"),
                    ("Spices", "Spices"),
                    ("Sauces", "Sauces"),
                    ("Alcohol", "Alcohol"),
                    ("Liquids", "Liquids"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fats",
            field=models.FloatField(
                help_text="amount of fats in kcal per 100 grams",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="proteins",
            field=models.FloatField(
                help_text="amount of proteins in kcal per 100 grams",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("calories__gte", 0.0)), name="calories >= 0"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("proteins__gte", 0.0)), name="proteins >= 0"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("fats__gte", 0.0)), name="fats >= 0"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("carbs__gte", 0.0)), name="carbs >= 0"
            ),
        ),
    ]
