# Generated by Django 4.1.7 on 2023-04-02 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("culinary", "0002_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
