# Generated by Django 4.1.7 on 2023-03-25 05:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("culinary", "0003_fridge"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtensilConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_value",
                    models.FloatField(
                        help_text="conversion value in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culinary.ingredient",
                    ),
                ),
                (
                    "utensil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culinary.measure",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="utensilconversion",
            constraint=models.CheckConstraint(
                check=models.Q(("standard_value__gte", 0.0)), name="standard_value >= 0"
            ),
        ),
    ]
