# Generated by Django 4.1.7 on 2023-03-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("culinary", "0004_utensilconversion_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="utensilconversion",
            constraint=models.UniqueConstraint(
                fields=("utensil", "ingredient"),
                name="utensil and ingredient combination must be unique",
            ),
        ),
    ]
