# Generated by Django 4.1.7 on 2023-03-26 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "culinary",
            "0005_utensilconversion_utensil and ingredient combination must be unique",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="culinary.ingredient",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="culinary.measure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="")),
                ("portions", models.PositiveSmallIntegerField()),
                ("total_time", models.TimeField()),
                ("instructions", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        related_name="favorites", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        through="culinary.IngredientUsage", to="culinary.ingredient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingredientusage",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="culinary.recipe"
            ),
        ),
    ]
